name: Node.js CI

on:
  push:
    branches:
      - master
      - main
      - qa/**
  pull_request:
    branches:
      - master
      - main
      - qa/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
<<<<<<< HEAD
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node-version }}"
=======
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
>>>>>>> 8d9797e (Improve error handling in API requests)
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test --if-present